-name: install nginx and run nginx
  hosts: web
  become: yes # it is equal to root access and ahoc command
  tasks:
    -name: install the nginx client
      ansible.builtin.dnf:
        name: nginx
        state: latest
    -name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enable: yes
