- name: Varible Declaration At Task Level
  hosts: localhost
  vars:
    course: "Devops"
    duration: "120 HRS"
    trainer: "Siva Kumar M"
  tasks:
  - name: print task variable
    vars:
      course: "Devops-Ansible"
    ansible.builtin.debug:
      msg: "Hi. i am learning {{course}} from {{trainer}} in a duration of {{duration}}"

  - name: print task variable
    vars:
      course: "Devops-Terraform"
    ansible.builtin.debug:
      msg: "Hi. i am learning {{course}} from {{trainer}} in a duration of {{duration}}"