- name: Varible Declaration At Task Level
  hosts: localhost
  vars:
    course: "Devops"
    duration: "120 HRS"
    trainer: "Siva Kumar M"
  tasks:
    - name: Accessing the Play variables
      ansible.builtin.debug:
        msg: "Hi, i am learning {{course}} from {{trainer}} in a duration of {{duration}}"
  
  tasks:
    - name: Accessing the Task level variable
      vars:
        course: "Devops-Ansible"
      ansibel.builtin.debug:
        msg: "Hi. i am learning {{course}} from {{trainer}} in a duration of {{duration}}"
      
