- name: Varibles accessing from args
  hosts: localhost
  tasks:
  - name: Access the argument
    ansible.builtin.debug:
      msg: "HI {{PERSON}} {{WISHES}}"

# To execute the below command
# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 09-vars-args.yaml -e PERSON=GOutham -e WISHES=GoodMorning