- name: Varibles accessing from args
  hosts: localhost
  tasks:
  - name: Access the argument
    ansible.builtin.debug:
      msg: "HI {{PERSON}} {{WISHES}}"

# To execute the below command
# ansible 