- name: print min and max
  hosts: localhost
  vars:
    ages: [12,25,62,54,63]
  tasks:
  - name: to print min and max ages
    ansible.builtin.debug:
      msg: "To print min ages {{ ages | min }}, To print max ages {{ ages | max }}"


- name: print remove duplicates
  hosts: localhost
  vars:
    numbers: [12,25,62,54,63,25,63]
  tasks:
  - name: to print min and max ages
    ansible.builtin.debug:
      msg: "To print min ages {{ numbers | unique}}"