
- name: install the libraries
  hosts: localhost
  become: yes
  tasks:
  - name: installing them using loops
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.latest}}"
    loop:
    - { name: 'mysql', state: latest}
    - { name: 'nginx', state: absent}
    - { name: 'postfix', state: latest}
  